// Generated by https://quicktype.io

export interface Dashboard {
  data: DataDashboard;
}

export interface DataDashboard {
  completed_orders: number;
  total_orders: number;
  products: number;
}
