// Generated by https://quicktype.io

export interface Category {
  data: CategoryData[];
}

export interface CategoryData {
  id: string;
  name: string;
  active: string;
  created_at: string;
  updated_at: string;
}
