// Generated by https://quicktype.io

export interface Dashboard {
  data: DataDashboard;
}

export interface DataDashboard {
  admins: number;
  clients: number;
  farmers: number;
  total: number;
}
