// Generated by https://quicktype.io

export interface Suggestions {
  data: SuggestionData[];
}

export interface SuggestionData {
  id: string;
  user_id: string;
  suggestion: string;
  finished: string;
  created_at: string;
  updated_at: string;
}
