// Generated by https://quicktype.io

export interface Units {
  data: UnitsData[];
}

export interface UnitsData {
  id: string;
  name: string;
  code: string;
  active: string;
  created_at: string;
  updated_at: string;
}
