// Generated by https://quicktype.io

export interface Users {
  data: usersData[];
}

export interface usersData {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  email_verified_at: null;
  created_at: string;
  updated_at: string;
}
