// Generated by https://quicktype.io

export interface Users {
  data: UsersData[];
}

export interface UsersData {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  role: string;
  created_at: string;
  updated_at: string;
}
